name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate test coverage
      run: ./gradlew jacocoTestReport

    - name: Run SonarCloud analysis
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=Rsyu_java-project-71
          -Dsonar.organization=rsyu
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

