name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Сборка проекта
        run: ./gradlew build --no-daemon

      - name: Запуск Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Запуск тестов
        run: ./gradlew test

